/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `opas_vigilancia_sindromica` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci */;
USE `opas_vigilancia_sindromica`;

CREATE TABLE IF NOT EXISTS `sintomas` (
  `nr_atendimento` varchar(15) NOT NULL DEFAULT '',
  `unidade_atendimento` varchar(50) DEFAULT NULL,
  `data_hora_atendimento` timestamp NULL DEFAULT NULL,
  `dt_nascimento` date DEFAULT NULL,
  `sg_sexo` char(1) DEFAULT NULL,
  `cid10` char(50) DEFAULT NULL,
  `evolucao` text DEFAULT NULL,
  `uf` char(2) DEFAULT NULL,
  `municipio` char(50) DEFAULT NULL,
  `bairro` char(50) DEFAULT NULL,
  `data_hora_fechamento` timestamp NULL DEFAULT NULL,
  `sintomas` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`nr_atendimento`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
